export const financeCapabilityManifest = [
  {
    apiOperation: "getFinancePlaybook",
    capability: "policy.playbook",
    mcpTool: "get_finance_playbook",
    mode: "read",
    requiredScope: "finances:read",
  },
  {
    apiOperation: "setupFinances",
    capability: "workflow.setup",
    mcpTool: "setup_finances",
    mode: "write",
    requiredScope: "finances:write",
  },
  {
    apiOperation: "maintainFinances",
    capability: "workflow.maintain",
    mcpTool: "maintain_finances",
    mode: "write",
    requiredScope: "finances:write",
  },
  {
    apiOperation: "getFinanceSnapshot",
    capability: "reporting.snapshot",
    mcpTool: "get_finance_snapshot",
    mode: "read",
    requiredScope: "finances:read",
  },
  {
    apiOperation: "getFinanceMaintenanceHistory",
    capability: "workflow.maintenance_history",
    mcpTool: "get_finance_maintenance_history",
    mode: "read",
    requiredScope: "finances:read",
  },
  {
    apiOperation: "getFinancialProfile",
    capability: "profile.read",
    mcpTool: "get_financial_profile",
    mode: "read",
    requiredScope: "finances:read",
  },
  {
    apiOperation: "updateFinancialProfile",
    capability: "profile.update",
    mcpTool: "update_financial_profile",
    mode: "write",
    requiredScope: "finances:write",
  },
  {
    apiOperation: "getFinanceBudget",
    capability: "budget.read",
    mcpTool: "get_finance_budget",
    mode: "read",
    requiredScope: "finances:read",
  },
  {
    apiOperation: "createFinanceBudget",
    capability: "budget.create",
    mcpTool: "create_finance_budget",
    mode: "write",
    requiredScope: "finances:write",
  },
  {
    apiOperation: "reviseFinanceBudget",
    capability: "budget.revise",
    mcpTool: "revise_finance_budget",
    mode: "write",
    requiredScope: "finances:write",
  },
  {
    apiOperation: "approveFinanceBudget",
    capability: "budget.approve",
    mcpTool: "approve_finance_budget",
    mode: "write",
    requiredScope: "finances:write",
  },
  {
    apiOperation: "getFinanceBudgetStatus",
    capability: "budget.status",
    mcpTool: "get_finance_budget_status",
    mode: "read",
    requiredScope: "finances:read",
  },
  {
    apiOperation: "listFinanceGoals",
    capability: "goal.list",
    mcpTool: "list_finance_goals",
    mode: "read",
    requiredScope: "finances:read",
  },
  {
    apiOperation: "manageFinanceGoal",
    capability: "goal.manage",
    mcpTool: "manage_finance_goal",
    mode: "write",
    requiredScope: "finances:write",
  },
  {
    apiOperation: "listFinanceAccounts",
    capability: "account.list",
    mcpTool: "list_finance_accounts",
    mode: "read",
    requiredScope: "finances:read",
  },
  {
    apiOperation: "startFinanceAccountConnection",
    capability: "account.connection_start",
    mcpTool: "start_finance_account_connection",
    mode: "external",
    requiredScope: "finances:write",
  },
  {
    apiOperation: "getFinanceAccountConnection",
    capability: "account.connection_read",
    mcpTool: "get_finance_account_connection",
    mode: "read",
    requiredScope: "finances:read",
  },
  {
    apiOperation: "syncFinanceAccounts",
    capability: "account.sync",
    mcpTool: "sync_finance_accounts",
    mode: "external",
    requiredScope: "finances:write",
  },
  {
    apiOperation: "updateFinanceAccount",
    capability: "account.update",
    mcpTool: "update_finance_account",
    mode: "write",
    requiredScope: "finances:write",
  },
  {
    apiOperation: "disconnectFinanceAccount",
    capability: "account.disconnect",
    mcpTool: "disconnect_finance_account",
    mode: "external",
    requiredScope: "finances:write",
  },
  {
    apiOperation: "listFinanceTransactions",
    capability: "ledger.transaction_list",
    mcpTool: "list_finance_transactions",
    mode: "read",
    requiredScope: "finances:read",
  },
  {
    apiOperation: "getFinanceTransaction",
    capability: "ledger.transaction_read",
    mcpTool: "get_finance_transaction",
    mode: "read",
    requiredScope: "finances:read",
  },
  {
    apiOperation: "reviewFinanceReceipt",
    capability: "ledger.receipt_review",
    mcpTool: "review_finance_receipt",
    mode: "read",
    requiredScope: "finances:read",
  },
  {
    apiOperation: "addFinanceTransaction",
    capability: "ledger.transaction_add",
    mcpTool: "add_finance_transaction",
    mode: "write",
    requiredScope: "finances:write",
  },
  {
    apiOperation: "updateFinanceTransaction",
    capability: "ledger.transaction_update",
    mcpTool: "update_finance_transaction",
    mode: "write",
    requiredScope: "finances:write",
  },
  {
    apiOperation: "removeFinanceTransaction",
    capability: "ledger.transaction_remove",
    mcpTool: "remove_finance_transaction",
    mode: "write",
    requiredScope: "finances:write",
  },
  {
    apiOperation: "splitFinanceTransaction",
    capability: "ledger.transaction_split",
    mcpTool: "split_finance_transaction",
    mode: "write",
    requiredScope: "finances:write",
  },
  {
    apiOperation: "classifyFinanceTransactions",
    capability: "ledger.transaction_classify",
    mcpTool: "classify_finance_transactions",
    mode: "write",
    requiredScope: "finances:write",
  },
  {
    apiOperation: "linkFinanceTransactions",
    capability: "ledger.transaction_link",
    mcpTool: "link_finance_transactions",
    mode: "write",
    requiredScope: "finances:write",
  },
  {
    apiOperation: "getFinanceCategories",
    capability: "ledger.category_list",
    mcpTool: "get_finance_categories",
    mode: "read",
    requiredScope: "finances:read",
  },
  {
    apiOperation: "getFinanceLedgerHealth",
    capability: "ledger.health",
    mcpTool: "get_finance_ledger_health",
    mode: "read",
    requiredScope: "finances:read",
  },
  {
    apiOperation: "importFinanceTransactions",
    capability: "ledger.import",
    mcpTool: "import_finance_transactions",
    mode: "write",
    requiredScope: "finances:write",
  },
  {
    apiOperation: "exportFinanceData",
    capability: "ledger.export",
    mcpTool: "export_finance_data",
    mode: "read",
    requiredScope: "finances:read",
  },
  {
    apiOperation: "getFinanceInbox",
    capability: "inbox.read",
    mcpTool: "get_finance_inbox",
    mode: "read",
    requiredScope: "finances:read",
  },
  {
    apiOperation: "answerFinanceReview",
    capability: "inbox.answer",
    mcpTool: "answer_finance_review",
    mode: "write",
    requiredScope: "finances:write",
  },
  {
    apiOperation: "listFinanceMerchants",
    capability: "merchant.list",
    mcpTool: "list_finance_merchants",
    mode: "read",
    requiredScope: "finances:read",
  },
  {
    apiOperation: "updateFinanceMerchant",
    capability: "merchant.update",
    mcpTool: "update_finance_merchant",
    mode: "write",
    requiredScope: "finances:write",
  },
  {
    apiOperation: "mergeFinanceMerchants",
    capability: "merchant.merge",
    mcpTool: "merge_finance_merchants",
    mode: "write",
    requiredScope: "finances:write",
  },
  {
    apiOperation: "listFinanceRules",
    capability: "rule.list",
    mcpTool: "list_finance_rules",
    mode: "read",
    requiredScope: "finances:read",
  },
  {
    apiOperation: "manageFinanceRule",
    capability: "rule.manage",
    mcpTool: "manage_finance_rule",
    mode: "write",
    requiredScope: "finances:write",
  },
  {
    apiOperation: "listFinanceRecurringItems",
    capability: "recurring.list",
    mcpTool: "list_finance_recurring_items",
    mode: "read",
    requiredScope: "finances:read",
  },
  {
    apiOperation: "manageFinanceRecurringItem",
    capability: "recurring.manage",
    mcpTool: "manage_finance_recurring_item",
    mode: "write",
    requiredScope: "finances:write",
  },
  {
    apiOperation: "getFinanceCashflow",
    capability: "reporting.cashflow",
    mcpTool: "get_finance_cashflow",
    mode: "read",
    requiredScope: "finances:read",
  },
  {
    apiOperation: "getFinanceWealthSummary",
    capability: "reporting.wealth",
    mcpTool: "get_finance_wealth_summary",
    mode: "read",
    requiredScope: "finances:read",
  },
] as const satisfies ReadonlyArray<{
  apiOperation: string;
  capability: string;
  mcpTool: string;
  mode: "external" | "read" | "write";
  requiredScope: "finances:read" | "finances:write";
}>;

export type FinanceCapability = (typeof financeCapabilityManifest)[number]["capability"];
