import type { goals, motives, reminders, taskProjects } from "@personal-os/database";
import { addLocalDays, localDateAt, localDateTimeToUtc, localDateToIso } from "@personal-os/domain";

type Goal = typeof goals.$inferInsert;
type Motive = typeof motives.$inferInsert;
type Commitment = typeof reminders.$inferInsert;
type Project = typeof taskProjects.$inferInsert;

/** Alex Morgan's fictional planning story. Stable IDs also allow a planning-only local refresh. */
export function demoPlanningStory(userId: string, inboxId: string, now: Date) {
  const id = (record: number) =>
    `${userId.slice(0, 8)}-0000-4000-8000-${record.toString(16).padStart(12, "0")}`;
  const timezone = "America/New_York";
  const today = localDateAt(now, timezone);
  const day = (offset: number) => localDateToIso(addLocalDays(today, offset));
  const at = (offset: number, hour = 17) =>
    localDateTimeToUtc(addLocalDays(today, offset), hour * 60, timezone);
  const ago = (days: number) => new Date(now.getTime() - days * 86_400_000);
  const personal = id(231);
  const work = id(232);
  const shopping = id(233);
  const goal = (
    record: number,
    title: string,
    description: string,
    status: Goal["status"],
    progress: number,
    target: number | null,
  ): Goal => ({
    id: id(record),
    userId,
    title,
    description,
    status,
    progress,
    targetDate: target === null ? null : day(target),
    createdAt: ago(45),
    updatedAt: ago(1),
  });
  const goalRows = [
    goal(
      210,
      "Build a sustainable focus rhythm",
      "Protect two 90-minute planning blocks on four weekdays and close the laptop by 6:30. Three weeks into the experiment: mornings work well; Thursday meetings still spill over. Success means steady creative work and enough energy for people afterward.",
      "active",
      64,
      28,
    ),
    goal(
      211,
      "Build a $12,000 breathing-room fund",
      "Alex has set aside $7,200 for three months of essentials. Cancel unused subscriptions, automate $400 each payday, and keep the buffer separate from travel savings. This is permission to make thoughtful career choices, not a race to spend less on everything.",
      "active",
      60,
      120,
    ),
    goal(
      800,
      "Open Harbor Arts Center's autumn program",
      "Welcome 20 local artists into an affordable autumn workshop series. Funding and the teaching roster are confirmed; room access, volunteer training, and participant invitations are underway. Open with a dependable small program rather than adding more classes than the team can support.",
      "active",
      72,
      18,
    ),
    goal(
      801,
      "Run the neighborhood 10K comfortably",
      "Build from two short runs to three easy sessions a week. Finish smiling rather than chasing a personal best. Four of ten training weeks are complete; leave recovery days around the opening weekend and run with Priya on Saturdays.",
      "active",
      40,
      42,
    ),
    goal(
      802,
      "Make Sunday dinner a monthly tradition",
      "Host six relaxed dinners this year, with room for friends who are new to the city. Two dinners happened, one was postponed, and the next is penciled in. A soup, a loaf of bread, and a long conversation count as a successful evening.",
      "active",
      33,
      100,
    ),
    goal(
      803,
      "Print a small book of neighborhood photographs",
      "A 24-page collection of ordinary New York mornings: laundromats, corner stores, and the walk to the river. Twelve images are shortlisted. Deliberately paused until the autumn program opens; keep taking pictures without turning the hobby into another deadline.",
      "paused",
      35,
      null,
    ),
    goal(
      804,
      "Move everyday banking to one clear system",
      "Consolidated bill payments, renamed savings buckets, and put rent and utilities on autopay. The first clean monthly review is complete. Keep the lightweight Friday check-in; there is no need to keep redesigning a system that now works.",
      "completed",
      100,
      -12,
    ),
    goal(
      805,
      "Make the apartment a place to unwind",
      "Cleared the bedroom desk, donated two boxes of unused equipment, and made a small reading corner. The living room can now hold dinner guests without a last-minute cleanup sprint. Maintenance belongs in small tasks, not an endlessly reopening goal.",
      "completed",
      100,
      -24,
    ),
  ];
  const motive = (record: number, title: string, detail: string, isActive = true): Motive => ({
    id: id(record),
    userId,
    title,
    detail,
    isActive,
    createdAt: ago(60),
    updatedAt: ago(2),
  });
  const motiveRows = [
    motive(
      212,
      "Calm momentum",
      "I do my best work when the week has breathing room. Prefer a small promise kept over an ambitious plan rescued at midnight. Leave space between demanding meetings and don't treat every free hour as capacity.",
    ),
    motive(
      213,
      "Intentional follow-through",
      "Finish the useful version before starting another project. When something no longer matters, cancel it honestly instead of carrying it as background guilt. A clear no is kinder to the team than a vague maybe.",
    ),
    motive(
      810,
      "People should not get my leftover energy",
      "Call Mom while I still have something to say, keep dinner with Sam off the work calendar, and show up for friends. A successful week includes being present at home, even when opening week is busy.",
    ),
    motive(
      811,
      "Make complicated things feel approachable",
      "Create programs that respect beginners. Use plain language, listen to participants, and explain what to bring before designing another poster. At Harbor Arts Center, a first-time visitor should feel as welcome as an established artist.",
    ),
    motive(
      812,
      "Strength for ordinary life",
      "Run for the feeling afterward, carry groceries comfortably, and sleep enough to be patient. Consistency beats intensity. A short easy run is useful; pushing through pain to protect a streak is not.",
    ),
    motive(
      813,
      "Turn every hobby into a side business",
      "An old rule that made photography feel like client work. Retired it after noticing that every walk became content research. Keep the camera; let the newsletter and print shop wait.",
      false,
    ),
    motive(
      814,
      "Say yes to every visible opportunity",
      "This helped early in my career, but it now fragments the week. Paused while I practice choosing the work I can finish well. Revisit after opening weekend, rather than accepting panels and extra projects automatically.",
      false,
    ),
  ];
  const project = (
    record: number,
    listId: string,
    name: string,
    why: string,
    notes: string,
    target: number,
    lifecycle: Project["lifecycle"] = "open",
  ): Project => ({
    id: id(record),
    userId,
    listId,
    name,
    normalizedName: name.toLowerCase(),
    why,
    notes,
    lifecycle,
    targetDate: day(target),
    createdAt: ago(35),
    updatedAt: ago(1),
    completedAt: lifecycle === "completed" ? ago(12) : null,
  });
  const projectRows = [
    project(
      240,
      personal,
      "Quarterly reset",
      "Make room for people, health, and a calmer home.",
      "Finish the finance cleanup and plan the next dinner. Keep this list short enough to clear in a few weekends.",
      21,
    ),
    project(
      241,
      work,
      "Quarterly reset",
      "Give Harbor Arts Center a clear plan backed by participant feedback.",
      "Review attendance and scholarship requests, write the board packet, and choose which classes to fund next quarter.",
      14,
    ),
    project(
      242,
      work,
      "Autumn program opening",
      "Make the first workshop welcoming for new neighbors.",
      "Opening cohort: 20 artists. Maya coordinates instructors; Alex owns room readiness, access needs, and the volunteer rota. Keep a weather fallback for the outdoor ceramics demonstration.",
      18,
    ),
    project(
      820,
      personal,
      "Neighborhood 10K",
      "Build fitness that survives a busy work week.",
      "Three easy sessions at most. Saturday river loop with Priya; rest after long runs. Shoes are fine for now.",
      42,
    ),
    project(
      821,
      personal,
      "Sunday dinner club",
      "Make friendship part of the calendar instead of a someday intention.",
      "Six guests, one vegetarian main, one shared playlist. Ask about allergies before deciding the menu.",
      9,
    ),
    project(
      822,
      personal,
      "Breathing-room fund",
      "Create enough financial room to make patient decisions.",
      "$7,200 of $12,000 saved. Keep emergency savings separate from the Lisbon trip. Review subscriptions before cutting the small rituals that make the week pleasant.",
      120,
    ),
    project(
      823,
      personal,
      "Apartment reset",
      "Make home feel restful without buying a new version of everything.",
      "Donation drop-off, bedroom cleanup, and reading corner are done. Keep a photo of the finished room as a reminder that enough can be enough.",
      -12,
      "completed",
    ),
  ];
  const task = (
    record: number,
    title: string,
    listId: string,
    projectRecord: number | null,
    notes: string,
    why: string,
    options: Partial<Commitment> = {},
  ): Commitment => ({
    id: id(record),
    userId,
    kind: "task",
    title,
    notes,
    taskWhy: why,
    taskListId: listId,
    taskProjectId: projectRecord === null ? null : id(projectRecord),
    taskLifecycle: "open",
    taskRevision: 1,
    status: "inbox",
    priority: "medium",
    estimateMinutes: 30,
    tags: [],
    timezone,
    dueAt: null,
    scheduledAt: null,
    completedAt: null,
    taskCancelledAt: null,
    deletedAt: null,
    createdAt: ago(7),
    updatedAt: ago(1),
    ...options,
  });
  const completed = (days: number): Partial<Commitment> => ({
    taskLifecycle: "completed",
    status: "completed",
    completedAt: ago(days),
    updatedAt: ago(days),
  });
  const cancelled = (days: number): Partial<Commitment> => ({
    taskLifecycle: "cancelled",
    status: "cancelled",
    taskCancelledAt: ago(days),
    updatedAt: ago(days),
  });
  const taskRows = [
    task(
      201,
      "Draft weekly program update",
      work,
      241,
      "In progress: enrollment figures and instructor notes are drafted. Add the two room-access fixes, explain the supply delay plainly, and send Maya a version she can skim in three minutes.",
      "Help the team make decisions from the same evidence.",
      { priority: "high", dueAt: at(0, 16), estimateMinutes: 45, tags: ["writing", "arts-center"] },
    ),
    task(
      202,
      "Compare renters insurance renewals",
      inboxId,
      null,
      "The current policy renews in three weeks. Compare the deductible and bike coverage before looking at price; save the two best quotes for the Friday money review.",
      "Protect the emergency fund from an avoidable surprise.",
      { estimateMinutes: 40, tags: ["home", "money"] },
    ),
    task(
      203,
      "Review monthly subscriptions",
      personal,
      822,
      "Music and the running app stay. Check whether the magazine subscription is still used, cancel the duplicate cloud backup, and note the real monthly savings.",
      "Fund the buffer without removing everything enjoyable.",
      {
        dueAt: at(1),
        scheduledAt: at(1, 14),
        status: "scheduled",
        tags: ["money"],
        estimateMinutes: 30,
      },
    ),
    task(
      204,
      "Book dentist appointment",
      personal,
      240,
      "Booked the morning appointment at Broadway Dental. Added a travel buffer and confirmed the insurance details.",
      "Keep preventive care out of the pile of postponed admin.",
      { ...completed(2), dueAt: at(-2, 12), estimateMinutes: 15, tags: ["health"] },
    ),
    task(
      206,
      "Replace spare charging cable",
      shopping,
      null,
      "Cancelled after finding the spare in the camera bag. No purchase needed.",
      "Check what I own before buying another copy.",
      { ...cancelled(1), priority: "low", estimateMinutes: 10, tags: ["home"] },
    ),
    task(
      207,
      "Compare desk lamps",
      shopping,
      null,
      "An impulse-research task from the apartment reset. The existing lamp works after replacing its bulb; keep this in Trash as a recoverable example.",
      "Avoid reopening a finished home project.",
      { deletedAt: ago(2), priority: "low", tags: ["home"] },
    ),
    task(
      208,
      "Prepare opening-weekend checklist",
      work,
      242,
      "List the owner and fallback for each opening-day risk. Volunteers need a one-page guide to room access, late arrivals, and the rain plan.",
      "Let the team respond calmly when something unexpected happens.",
      { dueAt: at(4), estimateMinutes: 50, tags: ["arts-center", "planning"] },
    ),
    task(
      900,
      "Confirm accessible routes through the workshop rooms",
      work,
      242,
      "In progress: the entrance ramp is checked. Measure the ceramics-room aisle, move the supply cart, and confirm an accessible restroom route with Jo before marking this complete.",
      "Every participant should be able to reach the workshop comfortably.",
      {
        priority: "high",
        dueAt: at(0, 15),
        scheduledAt: at(0, 10),
        status: "scheduled",
        estimateMinutes: 90,
        tags: ["facilities", "accessibility"],
      },
    ),
    task(
      901,
      "Send Maya the revised workshop invitation",
      work,
      242,
      "The draft is ready but still lists the old studio entrance. Correct the address, explain that materials are included, and add the scholarship contact before sending.",
      "Help people arrive prepared and feel welcome.",
      { priority: "high", dueAt: at(-1, 16), estimateMinutes: 15, tags: ["arts-center", "people"] },
    ),
    task(
      902,
      "Summarize the last three participant conversations",
      work,
      242,
      "In progress: two conversations are summarized. Finish Jordan's notes, include the evening-access concern, and separate requested classes from barriers to attending.",
      "Plan around the people who need access most, rather than only the loudest suggestions.",
      { dueAt: at(2), estimateMinutes: 75, tags: ["research"] },
    ),
    task(
      903,
      "Invite the final five scholarship participants",
      work,
      242,
      "Fifteen participants have confirmed. Ask the library and youth center to share the remaining scholarship places; keep space for people who have never taken an art class.",
      "Make the program available beyond the usual mailing list.",
      { dueAt: at(5), estimateMinutes: 40, tags: ["arts-center", "people"] },
    ),
    task(
      904,
      "Agree the opening-weekend safety and capacity plan",
      work,
      242,
      "Agreed room capacities, first-aid coverage, and the weather cancellation threshold with Maya and the facilities team. The signed plan is in the shared operations folder.",
      "Give volunteers clear decisions before opening-day pressure arrives.",
      {
        ...completed(3),
        priority: "high",
        dueAt: at(-3),
        estimateMinutes: 45,
        tags: ["arts-center"],
      },
    ),
    task(
      905,
      "Check the registration and scholarship paperwork",
      work,
      242,
      "Checked registration, scholarship requests, photo consent, and emergency contacts. Added plain-language explanations and printed copies for people who prefer to register in person.",
      "Keep paperwork from becoming a barrier to joining.",
      { ...completed(5), estimateMinutes: 60, tags: ["operations"] },
    ),
    task(
      906,
      "Prepare a concise board-packet narrative",
      work,
      241,
      "Use the enrollment and scholarship figures from the weekly update. Include participant feedback and the one funding decision the board needs to make; leave detailed budgets in the appendix.",
      "Make the important decision easy to find.",
      { dueAt: at(7, 12), estimateMinutes: 60, tags: ["writing", "leadership"] },
    ),
    task(
      907,
      "Add a second ceramics session before opening",
      work,
      242,
      "Cancelled because kiln capacity and instructor hours are already committed. Revisit after the first cohort rather than promising places we cannot support.",
      "Run the first program well before expanding it.",
      { ...cancelled(4), estimateMinutes: 120, tags: ["programming", "scope"] },
    ),
    task(
      908,
      "Plan next week's three easy runs",
      personal,
      820,
      "Choose two short morning routes and the Saturday river loop. Leave Friday clear after the volunteer rehearsal and keep a rainy-day option.",
      "Make movement fit the week I actually have.",
      { dueAt: at(2, 18), estimateMinutes: 15, tags: ["running"] },
    ),
    task(
      909,
      "Run the river loop with Priya",
      personal,
      820,
      "Easy conversational pace, about 5 km. Meet by the footbridge; walk the last stretch if the calf feels tight. Coffee afterward is part of the plan.",
      "Build consistency and friendship together.",
      {
        dueAt: at(1, 10),
        scheduledAt: at(1, 8),
        status: "scheduled",
        estimateMinutes: 50,
        tags: ["running", "friends"],
      },
    ),
    task(
      910,
      "Complete the first four-week training block",
      personal,
      820,
      "Eight easy runs and two longer outings completed. Energy is better on weeks with a real rest day. Keep the next block at the same pace.",
      "Measure the habit rather than compare race times.",
      { ...completed(4), estimateMinutes: 45, tags: ["running"] },
    ),
    task(
      911,
      "Choose a vegetarian main for Sunday dinner",
      personal,
      821,
      "Sam suggested mushroom lasagna; Priya is dairy-free. Compare it with the chickpea and tomato stew so everyone can eat the same meal.",
      "Make guests feel considered without cooking three separate dinners.",
      { dueAt: at(3, 18), estimateMinutes: 20, tags: ["friends", "cooking"] },
    ),
    task(
      912,
      "Confirm dinner guests and food allergies",
      personal,
      821,
      "Four yeses so far. Waiting on Jules and Nia; ask about allergies in the same message and cap the table at six.",
      "Make hosting warm and manageable.",
      { dueAt: at(-2, 18), estimateMinutes: 10, tags: ["friends"] },
    ),
    task(
      913,
      "Pick up beans, tomatoes, and bread flour",
      shopping,
      null,
      "Check the pantry first. Buy enough for six servings plus two lunches. Get the good tomatoes; skip the new serving dish.",
      "Keep the dinner simple and avoid a second grocery trip.",
      { dueAt: at(6, 18), estimateMinutes: 25, tags: ["groceries", "dinner"] },
    ),
    task(
      914,
      "Set the next two payday savings transfers",
      personal,
      822,
      "Review the checking balance before confirming $400 per payday. Keep rent money untouched and document the transfer dates in the Friday money note.",
      "Make the breathing-room goal repeatable instead of relying on willpower.",
      { dueAt: at(4, 12), estimateMinutes: 20, tags: ["money"] },
    ),
    task(
      915,
      "Cancel the duplicate cloud-backup subscription",
      personal,
      822,
      "Confirmed the remaining backup restores correctly, exported the old invoices, and cancelled the duplicate renewal. Savings: $12 each month.",
      "Remove a cost without losing a useful safety net.",
      { ...completed(6), estimateMinutes: 20, tags: ["money", "admin"] },
    ),
    task(
      916,
      "Donate the last box of unused equipment",
      personal,
      823,
      "Dropped off cables, the old keyboard, and the spare tripod. Kept only the equipment used in the last year.",
      "Finish the apartment reset rather than move the box to another corner.",
      { ...completed(12), estimateMinutes: 35, tags: ["home"] },
    ),
    task(
      917,
      "Collect three references for the photo-book sequence",
      inboxId,
      null,
      "Someday, after opening weekend: compare how small photo books pace quiet images. No buying supplies or creating a shop yet.",
      "Keep a creative possibility without turning it into urgent work.",
      { priority: "low", estimateMinutes: 25, tags: ["photography", "someday"] },
    ),
    task(
      918,
      "Write down the participant feedback from today's call",
      inboxId,
      null,
      "Capture the exact phrase about not knowing whether beginners are welcome while it is still fresh. Add the source and context so it informs the invitation wording.",
      "Keep small observations available for the next program decision.",
      { dueAt: at(0, 18), estimateMinutes: 5, tags: ["research", "capture"] },
    ),
  ];
  const reminder = (
    record: number,
    title: string,
    notes: string,
    offset: number | null,
    hour: number,
    options: Partial<Commitment> = {},
  ): Commitment => ({
    id: id(record),
    userId,
    kind: "reminder",
    title,
    notes,
    priority: "medium",
    status: offset === null ? "inbox" : "next",
    dueAt: offset === null ? null : at(offset, hour),
    timezone,
    tags: [],
    createdAt: ago(5),
    updatedAt: ago(1),
    completedAt: null,
    deletedAt: null,
    ...options,
  });
  const reminderRows = [
    reminder(
      200,
      "Send autumn program review agenda",
      "Include room access, scholarship places, and the rain-plan decision. Ask Maya for one question she wants answered before the meeting.",
      -1,
      16,
      { priority: "high", tags: ["arts-center"] },
    ),
    reminder(
      205,
      "Call Mom",
      "Ask how the garden is doing and pick a weekend for a visit. Call before dinner so neither of us is trying to multitask.",
      0,
      18,
      { priority: "low", tags: ["family"] },
    ),
    reminder(
      950,
      "Bring the library book back",
      "The essay collection is due today. Put it by the keys before leaving for the coffee shop.",
      0,
      17,
      { tags: ["errands"] },
    ),
    reminder(
      951,
      "Text Priya about the river-loop meeting point",
      "Confirm the footbridge and check the weather. If it pours, suggest breakfast and move the run rather than cancelling both.",
      1,
      7,
      { tags: ["running", "friends"] },
    ),
    reminder(
      952,
      "Check the insurance renewal email",
      "The quote link expires this week. Save the policy terms alongside the comparison task.",
      -3,
      12,
      { priority: "high", tags: ["admin"] },
    ),
    reminder(
      953,
      "Wish Jules a happy birthday",
      "Send a voice note about the museum afternoon, not just a thumbs-up in the group chat.",
      4,
      9,
      { tags: ["friends"] },
    ),
    reminder(
      954,
      "Take the camera on the next unhurried walk",
      "No shot list and nothing to post. Notice the morning light at the corner store.",
      null,
      9,
      { priority: "low", tags: ["photography"] },
    ),
    reminder(
      955,
      "Confirm the dentist appointment",
      "Confirmed the time and insurance by phone. The appointment is already on Calendar.",
      -2,
      10,
      { status: "completed", completedAt: ago(2), updatedAt: ago(2), tags: ["health"] },
    ),
    reminder(
      956,
      "Thank Nia for hosting dinner",
      "Sent a note and asked for the lentil-salad recipe. Offered to host the next one.",
      -4,
      19,
      {
        status: "completed",
        completedAt: ago(4),
        updatedAt: ago(4),
        priority: "low",
        tags: ["friends"],
      },
    ),
    reminder(
      957,
      "RSVP to the extra arts-network panel",
      "Declined this round to protect opening week. Ask about the next event after the autumn program settles.",
      -1,
      12,
      { status: "cancelled", priority: "low", tags: ["work", "boundaries"] },
    ),
  ];
  return {
    goals: goalRows,
    motives: motiveRows,
    taskProjects: projectRows,
    reminders: [...taskRows, ...reminderRows],
  };
}
