import { createHash } from "node:crypto";
import { chmod, rename, writeFile } from "node:fs/promises";
import path from "node:path";

function digest(value, length) {
  return createHash("sha256").update(value).digest("hex").slice(0, length);
}

export function deriveRuntimeIdentity({ commonDir, root }) {
  const repositoryId = digest(path.resolve(commonDir), 16);
  const runtimeId = digest(`${repositoryId}\0${path.resolve(root)}`, 12);
  return {
    composeProject: `ilo-${runtimeId}`,
    repositoryId,
    root: path.resolve(root),
    runtimeId,
  };
}

export function buildRuntimeOverlay(runtime) {
  const origin = `http://127.0.0.1:${runtime.port}`;
  return `${[
    "# Generated by .codex/scripts/worktree-runtime.mjs; do not edit.",
    `ILO_RUNTIME_ID=${runtime.runtimeId}`,
    `ILO_REPOSITORY_ID=${runtime.repositoryId}`,
    `ILO_RUNTIME_ROOT=${runtime.root}`,
    `COMPOSE_PROJECT_NAME=${runtime.composeProject}`,
    `LOCAL_WEB_PORT=${runtime.port}`,
    `APP_BASE_URL=${origin}`,
    `ALLOWED_ORIGINS=${origin},tauri://localhost,http://tauri.localhost`,
    `API_BASE_URL=${origin}`,
    `MCP_PUBLIC_URL=${origin}`,
    `MCP_RESOURCE_URL=${origin}/mcp`,
    `OAUTH_AUTHORIZATION_SERVER_URL=${origin}`,
    `GOOGLE_REDIRECT_URI=${origin}/v1/connectors/google/callback`,
    `X_REDIRECT_URI=${origin}/v1/x-bookmarks/callback`,
    "VITE_API_BASE_URL=",
    "VITE_PROXY_API_TARGET=http://127.0.0.1:8787",
    "VITE_PROXY_MCP_TARGET=http://127.0.0.1:8788",
  ].join("\n")}\n`;
}

export async function writeRuntimeOverlay(root, runtime) {
  const target = path.join(root, ".env.codex.local");
  const temporary = `${target}.${process.pid}.tmp`;
  await writeFile(temporary, buildRuntimeOverlay(runtime), { mode: 0o600 });
  await chmod(temporary, 0o600);
  await rename(temporary, target);
}

export function findOrphanProjects(projects, worktreeRoots, repositoryId) {
  return projects.filter(
    (project) =>
      project.repositoryId === repositoryId &&
      project.root &&
      !worktreeRoots.has(path.resolve(project.root)),
  );
}

export async function selectRuntimePort({ allocatePort, canBind, projectExists, storedPort }) {
  if (storedPort && (projectExists || (await canBind(storedPort)))) return storedPort;
  return allocatePort();
}

export function projectsFromDockerInspect(containers) {
  const projects = new Map();
  for (const container of containers) {
    const labels = container.Config?.Labels ?? {};
    const project = labels["com.docker.compose.project"];
    const repositoryId = labels["app.ilo.runtime.repository"];
    const root = labels["app.ilo.runtime.root"];
    if (!project || !repositoryId || !root) continue;
    projects.set(project, { project, repositoryId, root });
  }
  return [...projects.values()].sort((a, b) => a.project.localeCompare(b.project));
}

export async function reconcileOrphans({
  listProjects,
  listWorktreeRoots,
  prune,
  removeProject,
  repositoryId,
}) {
  const candidates = findOrphanProjects(
    await listProjects(),
    await listWorktreeRoots(),
    repositoryId,
  );
  if (!prune) return candidates;

  const removed = [];
  for (const candidate of candidates) {
    const currentRoots = await listWorktreeRoots();
    if (currentRoots.has(path.resolve(candidate.root))) continue;
    await removeProject(candidate);
    removed.push(candidate);
  }
  return removed;
}

export function worktreeRootsFromPorcelain(output) {
  const roots = new Set();
  for (const record of output.split("\0\0")) {
    const fields = record.split("\0").filter(Boolean);
    const worktree = fields.find((field) => field.startsWith("worktree "));
    const prunable = fields.some((field) => field === "prunable" || field.startsWith("prunable "));
    if (worktree && !prunable) roots.add(path.resolve(worktree.slice("worktree ".length)));
  }
  return roots;
}
